In [ ]:
import pandas as pd

#1
df = pd.read_csv("/content/students - students.csv")
#2
df.head()

#3
df.tail(10)

# 4
df.shape

# 5
df.columns

# 6
df.dtypes

# 7
df.info()

# 8
df.describe()

# 9
df.isnull().sum()

#10
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               200 non-null    object
 1   student_name             200 non-null    object
 2   gender                   200 non-null    object
 3   age                      198 non-null    float64
 4   semester                 200 non-null    int64
 5   attendance_percent       200 non-null    float64
 6   study_hours_per_day      200 non-null    float64
 7   assignment_average       196 non-null    float64
 8   quiz_average             200 non-null    float64
 9   mid_sem_score            200 non-null    float64
 10  previous_cgpa            200 non-null    float64
 11  lab_hours_per_week       199 non-null    float64
 12  online_activity_count    200 non-null    int64
 13  projects_completed       200 non-null    int64
 14  python_skill_level       200 non-null    object
 15  mathematics_skill        191 non-null    object
 16  engagement_score         200 non-null    float64
 17  predicted_score          200 non-null    float64
 18  grade                    200 non-null    object
 19  risk_level               200 non-null    object
 20  learning_recommendation  200 non-null    object
dtypes: float64(10), int64(3), object(8)
memory usage: 32.9+ KB

student_id                 200
student_name               123
gender                       2
age                          6
semester                     6
attendance_percent         166
study_hours_per_day         51
assignment_average         160
quiz_average               171
mid_sem_score              171
previous_cgpa              165
lab_hours_per_week          75
online_activity_count      130
projects_completed           6
python_skill_level           3
mathematics_skill            3
engagement_score           170
predicted_score            146
grade                        4
risk_level                   3
learning_recommendation      4
dtype: int64

In [ ]:
# 11
df[['student_name','gender','semester']]

# 12
df[df['semester'] == 3]

# 13
df[df['gender'] == 'Female']

# 14
df[df['previous_cgpa'] > 8.0]

# 15
df[df['attendance_percent'] < 75]

# 16
df[df['study_hours_per_day'] > 4]

# 17
df[df['python_skill_level'] == 'Advanced']

# 18
df[df['grade'] == 'A']

# 19
df[df['risk_level'] == 'High']

# 20
df.loc[df['predicted_score'] > 80, ['student_name','predicted_score']]

      student_name  predicted_score
3     Aditya Kumar             80.1
6     Aarav Mishra             83.6
11    Rahul Mishra             81.2
12    Aditya Verma             82.2
14    Kunal Sharma             95.9
..             ...              ...
190   Riya Chauhan             83.6
191     Isha Sinha             87.6
196  Arjun Chauhan             86.8
198    Priya Gupta             92.6
199   Vivaan Singh             89.3

[81 rows x 2 columns]

In [ ]:
# 21
df[(df['semester']==4) & (df['attendance_percent']>80)]

# 22
df[(df['previous_cgpa']>8) & (df['predicted_score']>75)]

# 23
df[df['semester'].isin([2,4])]

# 24
df[(df['gender']=='Female') & (df['python_skill_level']=='Advanced')]

# 25
df[df['study_hours_per_day'].between(2,5)]

# 26
df[df['grade'].isin(['A','B'])]

# 27
df[df['risk_level'].isin(['Medium','High'])]

# 28
df[df['mathematics_skill'].isin(['Good','Excellent'])]

# 29
df[(df['projects_completed']>=2) & (df['engagement_score']>70)]

# 30
df[(df['attendance_percent']>85) & (df['study_hours_per_day']>3) & (df['grade']=='A')]

,student_id,student_name,gender,age,semester,attendance_percent,study_hours_per_day,assignment_average,quiz_average,mid_sem_score,...,lab_hours_per_week,online_activity_count,projects_completed,python_skill_level,mathematics_skill,engagement_score,predicted_score,grade,risk_level,learning_recommendation
17,DS018,Arjun Sharma,Male,18.0,3,99.8,3.3,60.4,93.0,83.6,...,2.6,55,4,Intermediate,High,55.7,91.8,A,Low,Advanced Projects
28,DS029,Saurabh Gupta,Female,18.0,5,99.6,3.1,65.5,86.6,57.2,...,6.9,122,4,Intermediate,Medium,59.5,85.9,A,Low,Advanced Projects
53,DS054,Aryan Sinha,Female,22.0,8,91.0,5.1,55.3,54.1,76.2,...,2.5,51,0,Intermediate,Medium,67.6,85.6,A,Low,Advanced Projects
55,DS056,Aman Sharma,Male,19.0,6,90.7,4.1,74.3,93.6,86.3,...,2.5,164,0,Beginner,Medium,68.6,85.4,A,Low,Advanced Projects
71,DS072,Arjun Verma,Female,20.0,5,92.9,5.2,97.5,49.3,75.5,...,2.8,49,0,Intermediate,Medium,68.7,87.1,A,Low,Advanced Projects
73,DS074,Neha Pandey,Male,20.0,7,89.2,4.6,80.0,98.8,93.7,...,5.5,118,1,Beginner,Medium,68.5,96.3,A,Low,Advanced Projects
105,DS106,Nisha Singh,Male,19.0,6,85.3,5.8,50.2,80.4,63.8,...,1.4,43,0,Advanced,High,71.2,87.8,A,Low,Advanced Projects
106,DS107,Simran Singh,Female,18.0,4,94.1,3.9,46.7,95.9,79.8,...,1.7,151,4,Intermediate,Medium,66.8,86.4,A,Low,Advanced Projects
133,DS134,Riya Verma,Male,23.0,6,89.9,4.2,74.2,42.5,98.0,...,2.3,11,5,Intermediate,High,57.0,86.8,A,Low,Advanced Projects
198,DS199,Priya Gupta,Male,21.0,7,98.8,5.2,46.3,93.9,85.9,...,3.7,68,3,Advanced,Medium,71.7,92.6,A,Low,Advanced Projects
199,DS200,Vivaan Singh,Male,21.0,7,88.6,3.4,48.2,97.5,96.3,...,7.9,187,2,Advanced,Low,64.3,89.3,A,Low,Advanced Projects

In [ ]:
# 31
df.sort_values('predicted_score', ascending=False)

# 32
df.nlargest(10, 'predicted_score')

# 33
df.nsmallest(10, 'predicted_score')

# 34
df.loc[df['predicted_score'].idxmax()]

# 35
df.loc[df['predicted_score'].idxmin()]

# 36
df.sort_values('previous_cgpa', ascending=False)

# 37
df.sort_values(['semester','predicted_score'], ascending=[True,False])

# 38
df['score_rank'] = df['predicted_score'].rank(ascending=False)

# 39
df.nlargest(10, 'engagement_score')

# 40
df.loc[df['online_activity_count'].idxmax()]

student_id                                       DS034
student_name                              Aditya Singh
gender                                          Female
age                                               21.0
semester                                             8
attendance_percent                                57.5
study_hours_per_day                                1.6
assignment_average                                51.5
quiz_average                                      79.0
mid_sem_score                                     83.5
previous_cgpa                                      7.8
lab_hours_per_week                                 7.7
online_activity_count                              200
projects_completed                                   3
python_skill_level                            Beginner
mathematics_skill                                 High
engagement_score                                  43.2
predicted_score                                   72.4
grade                                                C
risk_level                                        High
learning_recommendation    Video Tutorials and Quizzes
score_rank                                       146.0
Name: 33, dtype: object

In [ ]:
# 41
df.groupby('semester')['predicted_score'].mean()

# 42
df.groupby('semester')['attendance_percent'].mean()

# 43
df.groupby('gender')['study_hours_per_day'].mean()

# 44
df['grade'].value_counts()

# 45
df['risk_level'].value_counts()

# 46
df.groupby('python_skill_level')['predicted_score'].mean()

# 47
df.groupby('mathematics_skill')['previous_cgpa'].mean()

# 48
df.groupby('semester')['engagement_score'].mean()

# 49
df.groupby('grade')['predicted_score'].agg(['max','min'])

# 50
df.groupby('semester').agg({
    'attendance_percent':'mean',
    'study_hours_per_day':'mean',
    'predicted_score':'mean',
    'student_id':'count'
}).rename(columns={'student_id':'num_students'})

,attendance_percent,study_hours_per_day,predicted_score,num_students
semester,,,,
3,79.284615,3.173077,77.084615,26
4,75.508571,3.617143,78.380000,35
5,73.623684,3.615789,79.244737,38
6,79.024242,3.654545,77.290909,33
7,78.608824,3.232353,77.473529,34
8,79.679412,3.197059,77.491176,34